import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#A17DC5",
    alignItems: "stretch",
    justifyContent: "space-evenly",
    color: "white",
    padding: 25,
    paddingTop: 100,
  },
  appText: {
    color: "white"
  },
  title: {
    color: "white",
    fontSize: 34,
    fontWeight: "bold",
    elevation: 3,
  },
  navbar: {
    flex: 0.3,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 50,
    position: "absolute",
    top: 60,
    left: 25,
    width: 340,
  },
  avatar: {
    backgroundColor: "white",
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  cardContainer: {
    marginTop: 40,
  },
  card: {
    backgroundColor: "#735295",
    borderRadius: 10,
    height: 200,
    marginBottom: 15,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    padding: 25,
  },
  cardText: {
    color: "white",
  },
  cardTitle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardSaveAmt: {
    fontWeight: "bold",
    color: "#14F4E7",
    fontSize: 20,
  },
  cardSaveTitle: {
    fontWeight: "bold",
    fontSize: 20,
    color: "white",
  },
  row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dateIndicator: {
    backgroundColor: "white",
    height: 30,
    width: 30,
    borderRadius: 15,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  viceModal: {
    padding: 20,
    backgroundColor: "#735295",
    marginVertical: 100,
    borderRadius: 15,
    height: 600,
    marginHorizontal: 15,
    elevation: 5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  viceModalContent: {
    display: "flex",
    flex: 0.5,
    flexDirection: "column",
    justifyContent: "space-evenly",
  },
  overlay: {
    backgroundColor: "rgba(0, 0, 0, 0.50)",
    paddingVertical: 25,
  },
  viceModalButton: {
    color: "white",
  },
  viceModalButtonOutline: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderColor: "white",
    borderWidth: 1.5
  },
  floatingActionButton: {
    position: "absolute",
    bottom: 50,
    right: 30,
    height: 50,
    width: 50,
    borderRadius: 25,
    backgroundColor: "#111111",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    borderColor: "#14F4E7",
    borderWidth: 2,
  },
  inlineInput: {
    color: "white",
    borderBottomColor: "white",
    borderBottomWidth: 1,
    flex: 0.8,
    paddingBottom: 2,
  },
});
